apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
  - name: mycnt2
    image: nginx
    ports:
      - containerPort: 80
        name: http
    volumeMounts:
    - mountPath: "usr/share/nginx/html"
      name: myvol2
  volumes:
  - name: myvol2
    persistentVolumeClaim:
      claimName: dev1-pvc
